---
Title: 'Installation guide'
---

# Prerequisites
For more information about the prerequisites for an installation of the HydroMT package
and related dependencies, please visit the documentation of
[HydroMT core](https://deltares.github.io/hydromt/latest/overview/installation.html#installation-guide)

# Installation

# Using Hydromt UWBM

To start using Hydromt UWBM, you only need to add this line to your projects dependencies:
`` "hydromt_uwbm @ git+https://github.com/Deltares-research/hydromt_uwbm" ``

# Developper installation
To generate a usable python development environment you’ll need to have uv installed.
You can simply install this from their [website](https://docs.astral.sh/uv/getting-started/installation/).

With uv installed, you can now add hydromt_uwbm to your environment in various ways:

1. CLI

- `cd <project_dir>`
- `uv add "hydromt_uwbm @ git+https://github.com/Deltares-research/hydromt_uwbm"`

2. pyproject.toml

- add `"hydromt_uwbm @ git+https://github.com/Deltares-research/hydromt_uwbm"` to the `dependencies` section in a pyproject.toml file.

3. enironment.yml

- add `- pip` to the dependencies list to ensure pip is installed
- add ``- pip:`` to specify a list of packages to install from pypi
- add ``"hydromt_uwbm @ git+https://github.com/Deltares-research/hydromt_uwbm"`` to the pip section.

After adding the dependency, install your updated environment. (with uv: `uv sync --all-extras`)
